# Reference this view as ecommerce_db_public__products_sheet1
catalog: ECOMMERCE_DB
schema: PUBLIC
table_name: PRODUCTS_SHEET1

dimensions:
  product_id:
    sql: '"PRODUCT_ID"'
    format: ID

  product_name:
    sql: '"PRODUCT_NAME"'

  category:
    sql: '"CATEGORY"'

  subcategory:
    sql: '"SUBCATEGORY"'

  list_price:
    sql: '"LIST_PRICE"'

  unit_cost:
    sql: '"UNIT_COST"'

measures:
  count:
    aggregate_type: count
